* Curator Front-End (React Framework)

The front-end website for Curator. Basically, the ~<video>~ tag inbetween user and creator.

** Terminology

- Curator :: The proper noun name of the entire platform.

- Channel :: A user on the site that has created Posts.

- Post :: A description of content and where to find it. Title, info section, URI, things like that.

** Goals

**** TODO Visitors will be able to see content (watch videos) hosted by external servers.
Started [2024-06-11 Tue 10:33]

AFAIK this is basically just going to be an HTML5 ~<video>~ tag with a customizable ~src~ URI.

**** TODO Visitors will be able to see all Posts from a single Channel.
Started [2024-06-11 Tue 10:33]

AFAIK this is just going to display a list of Posts from a database.

**** TODO Users will be able to discover content through Posts from Channels they Track.
Started [2024-06-11 Tue 10:33]

AFAIK this is going to require user authentication (Firebase?)

AFAIK this is just going to be an array of user identifiers within each user's data in the database that correspond to channels they have clicked the ~Track~ button for.

** Developers

To start the development server on =localhost:3000=:
#+begin_src shell
  npm run dev
#+end_src

