* Curator

The idea is that the large cost and liability of hosting a video-sharing website is actually storing and serving the video content, as it is large and bulky to send over networks. To mitigate that risk and cost away from the user-facing site (for example, onto creators themselves) would allow the website to rely less on predatory profit tactics, as well as allow each creator to decide what is allowed on their page or not. This model is basically cable TV but for the Internet.

** The Elephant

Curator is not YouTube: let me explain. YouTube "made it easy" for anyone to share videos they created to a wide audience. To do this, they decided to take on the costs of hosting and serving the video data itself. In doing so, they created a business that ran at a loss for many, many years, and had to climb themselves out of a hole into profitability using, in my opinion, predatory profit tactics, unfair revenue distribution, and more. The beast that is YouTube was created in the design of it from the beginning.

The major liability and cost of sharing videos is actually doing the sharing; hosting the video data and serving it to anyone who wants to watch. Now, if every video was 360p, the costs would be relatively low. But some people will be uploading 8k high-bitrate footage, while others will be uploading, well, footage from a potato. YouTube partially solves this by doing CPU-intensive (and therefore energy-intensive and more costly) transcoding to produce different, smaller versions of the original video. All of this balloons the costs that YouTube must pay just to operate, and in doing so "makes them" have to rake in profits at a ridiculous margin off of every user and creator. If a lot of money goes into the dumpster every month, the mindset is that you have to get as much as possible in each month.

That is why, with Curator, we take a different approach. It will not be as easy for just anybody to get their content on the site... but, at the same time, it will. This is because there will be a higher startup cost to actually hosting a video on the site: you need a video server on the internet that you have control over and can point to with a static URI. If the server goes away, so does the content hosted there. This means a creator may have full control over their content, even being able to alter and update it without having to re-upload. In fact, at Curator, you don't have to upload anything at all, except for when somebody watches your video. That's right, no more waiting: instant uploads.

FYI, if you get a million people watching your 8k high-bitrate video, that is going to be a lot of bandwidth, and you are going to have to plan for that or your video may become unwatchable for many.

As you can imagine, with this major liability and cost no longer on the website itself, the website itself may operate at a pretty low cost (these simple text fields amount to a few kilobytes maximum per post). A video post isn't much more than a title, info section, and a URI. Because of this, the website doesn't have to insert a crazy amount of ads into every page, inside of content, and more in order to offset this major risk and cost. Instead, the burden of the cost goes to those creating the content that is most costly. Somebody who just uploads 720p gaming commentaries or short clips to show their friends won't pay nearly as much (given they had the same rates on energy, bandwidth, etc). While this does make it so that the channels on Curator will be required to make money, that's kind of how video content on the internet works these days. Each channel has sponsors (sponsored segments, product placements, advertisements, and more) and other avenues like affiliate marketing that produce revenue so they can keep creating and sharing the content; it's a positive feedback loop with direct feedback from user to creator. At the same time, a creator is able to track their own viewer statistics, as every person who watches their video visits their own server; nobody can get in the way of that and lie to you about your audience.
